// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn4vxareW0-nbqXyAia-0nbC_C95mypUU',
    appId: '1:1002183148212:web:fd7c182dd0f1d6cb24cde1',
    messagingSenderId: '1002183148212',
    projectId: 'flows-5e64b',
    authDomain: 'flows-5e64b.firebaseapp.com',
    storageBucket: 'flows-5e64b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9YMbJM-CGQsfCc4Fgrc5h6NW21u8IFKc',
    appId: '1:1002183148212:android:4bd84076aeac864f24cde1',
    messagingSenderId: '1002183148212',
    projectId: 'flows-5e64b',
    storageBucket: 'flows-5e64b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59tfUkvfqGYGHLHtZbHM3QLugZsXG52o',
    appId: '1:1002183148212:ios:62b419cd1e662d2424cde1',
    messagingSenderId: '1002183148212',
    projectId: 'flows-5e64b',
    storageBucket: 'flows-5e64b.appspot.com',
    iosClientId: '1002183148212-14d4kd2gaqsas7eiho1pnaisvto6fkmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jeumpaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59tfUkvfqGYGHLHtZbHM3QLugZsXG52o',
    appId: '1:1002183148212:ios:62b419cd1e662d2424cde1',
    messagingSenderId: '1002183148212',
    projectId: 'flows-5e64b',
    storageBucket: 'flows-5e64b.appspot.com',
    iosClientId: '1002183148212-14d4kd2gaqsas7eiho1pnaisvto6fkmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jeumpaApp',
  );
}
